/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useSinglePlayerGame`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useBackgroundMusic`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useTurnTimer`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useSoundEffects`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Confetti`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ScaleBtn`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/ThemeContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useSinglePlayerGame`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useBackgroundMusic`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useTurnTimer`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useSoundEffects`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Confetti`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ScaleBtn`; params?: Router.UnknownOutputParams; } | { pathname: `/../utils/ThemeContext`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../hooks/useSinglePlayerGame${`?${string}` | `#${string}` | ''}` | `/../hooks/useBackgroundMusic${`?${string}` | `#${string}` | ''}` | `/../hooks/useTurnTimer${`?${string}` | `#${string}` | ''}` | `/../hooks/useSoundEffects${`?${string}` | `#${string}` | ''}` | `/../components/Confetti${`?${string}` | `#${string}` | ''}` | `/../components/ScaleBtn${`?${string}` | `#${string}` | ''}` | `/../utils/ThemeContext${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useSinglePlayerGame`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useBackgroundMusic`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useTurnTimer`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useSoundEffects`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Confetti`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ScaleBtn`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/ThemeContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
